Repository AY2425S2-CS2113-T13-3/tp, pull requests merged in 2025-03, with the labels that each got.

#56 updated deleteBook
  src/main/java/seedu/duke/book/BookManager.java
Labels: type.Bug

#60 added javadoc comments
  src/main/java/seedu/duke/book/BookManager.java
Labels: type.Task

#86 Added in junit test for bookmanagertest
  src/test/java/seedu/duke/book/BookManagerTest.java
Labels: type.Task

#142 Implemented the addBook function to the shelves
  src/main/java/seedu/duke/Shelving/Shelves/Shelf.java
  src/main/java/seedu/duke/Shelving/Shelves/Shelves.java
  src/main/java/seedu/duke/Shelving/ShelvesManager.java
  src/main/java/seedu/duke/book/Book.java
  src/main/java/seedu/duke/book/ShelfBookManager.java
  src/main/java/seedu/duke/library/Library.java
  src/test/java/seedu/duke/shelf/ShelfTest.java
Labels: priority.Low

#146 Java Doc
  src/main/java/seedu/duke/Shelving/Shelves/Shelf.java
  src/main/java/seedu/duke/Shelving/Shelves/Shelves.java
  src/test/java/seedu/duke/shelf/ShelfTest.java
Labels: priority.Low

#177 Fix listing shelf when deleted a book
  src/main/java/seedu/duke/shelving/shelves/Shelf.java
  src/test/java/seedu/duke/shelf/ListShelfCommandTest.java
Labels: type.Bug

#180 Fix bug on listing the shelf that is not in the section
  src/main/java/seedu/duke/exception/NoSuchSectionException.java
  src/main/java/seedu/duke/shelving/ShelvesManager.java
  src/main/java/seedu/duke/shelving/shelves/Shelf.java
  src/main/java/seedu/duke/shelving/shelves/Shelves.java
Labels: type.Bug, priority.Low

#184 Improve formatting
  src/main/java/seedu/duke/commands/ListShelfCommand.java
  src/main/java/seedu/duke/library/Library.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/shelving/ShelvesManager.java
  src/main/java/seedu/duke/shelving/shelves/Shelf.java
  src/main/java/seedu/duke/shelving/shelves/Shelves.java
  src/test/java/seedu/duke/shelf/ListShelfCommandTest.java
Labels: type.Enhancement

#188 Fix the loading of files
  src/main/java/seedu/duke/LeBook.java
  src/main/java/seedu/duke/library/Library.java
  src/main/java/seedu/duke/shelving/ShelvesManager.java
  src/main/java/seedu/duke/shelving/shelves/Shelf.java
  src/main/java/seedu/duke/shelving/shelves/Shelves.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/shelf/LibraryTest.java
  src/test/java/seedu/duke/shelf/ShelvesManagerTest.java
  src/test/java/seedu/duke/shelf/shelftest/AddTests.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Bug, priority.High

#191 squash minor bugs
  src/main/java/seedu/duke/book/BookManager.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/shelving/ShelvesManager.java
  src/main/java/seedu/duke/shelving/shelves/Shelf.java
  src/main/java/seedu/duke/shelving/shelves/Shelves.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/shelf/ListShelfCommandTest.java
Labels: type.Bug
